config/routes.rb
Blogtastic::Application.routes.draw do

  resources :posts do
    resources :comments
  end

  root 'welcome#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "Keith", password: "lobsters", only: :destroy

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name: "Keith", password: "lobsters", except: [:index, :show]

  def new
    @post = Post.new # this allows us to check for errors in our view and not have it blow up
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end  
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p>
    <%= link_to "x", [comment.post, comment], method: :delete, data: { confirm: "Are you sure this is spam?"} %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= comment.commenter %>
  </p>
   
  <p>
    <strong>>></strong>
    <%= comment.body %>
  </p>

</div>

app/views/comments/_form.html.erb
<div class="input_form commenting">
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br />
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogtastic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans:300,400|Josefin+Slab:400,600' rel='stylesheet' type='text/css'>
</head>
<body>

  <div class="overlay">
  </div>


  <div class="container">
    <div class="home">
      <%= link_to "Home", controller: "welcome"  %>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="input_form posting">
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>All posts</h1>
 

<table>
  <tr>
    <th>Title</th>
    <th>Comments</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, post_path(post) %></td>
      <td><%= post.comments.count %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post), method: :delete, data: {confirm: "Are you sure???"} %></td>
    </tr>
  <% end %>
</table>

<div class="nav">
<%= link_to "New Post!", new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>Time to get expressive</h1>

<%= render 'form' %>

<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<h2>
  <%= @post.title %>
 </h2>

<div class="blog-text">
  <%= @post.content %>
</div>

<div class="nav">
<%= link_to "Back", posts_path(@post) %>

<%= link_to "Edit", edit_post_path(@post) %>
</div>

<div class="comments_container">
  <h3>Comments</h3>
  <%= render @post.comments %>
</div>

<div class="after_comments">
  <h4>Add Comment:</h4>
  <%= render "comments/form" %>



</div>

app/views/welcome/index.html.erb
<div>
  <h1>It's Blogtastic!</h1>

  <%= link_to "The Blog", controller: "posts" %>

</div>